### ISSUE TITLE
meta.asc records user's first name, not login name

### ISSUE THREAD

**Issue by sgbeal** [Cortys/comic-backup#72]
The .meta.asc file included with each archive includes the user's first name. Any number of users may share the same first name, so that information is not at all useful for "watermarking" the archive. The user's login name should be recorded instead.

(Obviously, anyone who intends to share his backups will simply remove that file (or edit it to contain someone else's name!), so this isn't a "real" issue.)

**Comment by sgbeal** [comment]
Mine reports:

    data-username: Stephan

my user name is sgbeal, but i'm not seeing that anywhere else in the reader page. Presumably this means that the tiny digital watermarks are using the name "Stephan" as well?

PS: i'm using comixology.eu, not .com (the same as you, i presume, since we're both in Germany).

**Comment by sgbeal** [comment]
Question: might this be a side-effect of me using my Amazon account to log in, instead of my (old) Comixology account? i merged those accounts years ago when Amazon bought Comixology.

**Comment by Cortys** [comment]
That seems to be the reason. Using my Amazon account I also only get my first name there and a quick DOM search did not reveal another good way to identify the user either.

The `data-client-context` might be a viable alternative, assuming cmxlgy stores their session ids for some significant amount of time. Since this would increase the size of page watermarks I am however not really that eager to change this.

I think we should not "fix" as long as cmxlgy doesn't complain or provides a nicer alternative.

**Comment by sgbeal** [comment]
A session ID is probably not useful for a long-term watermark because they're not going to retain their logs for that long (i'm fairly sure, but not 100% certain, that the GDPR doesn't allow them to). In any case, i agree: it's not real bug. Until/unless Amazon complains, i would ignore it. You can't be held accountable if they don't provide unique-per-user info to watermark with :).
