### ISSUE TITLE
Save Directory Error

### ISSUE THREAD

**Issue by perrinaz** [Cortys/comic-backup#85]
When a directory is specified, say "D:\Downloads\Comixology" the addon appends a forward slash (/) and no files are saved.  The error given when "collect errors" is turned on is "Invalid Filename" and "onend" is not a function.

**Comment by perrinaz** [comment]
I do not know if this is still being maintained so I'll add this for anybody who experienced the same issues I did.  Basically, the directory option takes a single sub-directory that will be created in the Chrome downloads directory.  It does not accept any pathing (that I've been able to discover) so no absolute paths like I tried or even ..\path type directories.

**Comment by Cortys** [comment]
@perrinaz Thanks for reporting this. I currently don't have the time to maintain the project but I plan to properly deal with the currently open issues in the future.

The problem you describe is due to Chrome's security policy and cannot really be solved. I'll keep this open anyway as a reminder to add input validation to the download directory option so that absolute paths are rejected with a clear error message.

**Comment by Cortys** [comment]
Finally addressed this in the 2.4.1 release by providing a proper error message on invalid paths.
